apiVersion: apps/v1
kind: Deployment
metadata:
  name: jorel-game-deployment
  namespace: pranay
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jorel-game
  template:
    metadata:
      labels:
        app: jorel-game
    spec:
      containers:
        - name: jorel-game-container
          image: registry.gitlab.com/pranay00/jorel-k8s/game-php:0.1.0
          ports:
            - containerPort: 80
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName  
          imagePullPolicy: Always
      imagePullSecrets:
        - name: gitlab-registry-secret
