apiVersion: v1
kind: Service
metadata:
  name: jorel-game-service
  namespace: pranay
spec:
  selector:
    app: jorel-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
